version: '3.4'

services:
  rabbitmq2:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    container_name: rabbitmq2
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  userapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBIT_HOSTNAME: "rabbitmq"
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq2
